name: app_for_app

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  email_validator: ^3.0.0
  http: ^1.2.2
  logger: ^2.5.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
